export const data = {
  0: {
    id: "0",
    category: "root",
    isChecked: false,
    parentId: null,
    childCheckedCount: 0,
    children: ["1"],
  },
  1: {
    id: "1",
    category: "Electronics",
    isChecked: false,
    parentId: "0",
    childCheckedCount: 0,
    children: ["1.1", "1.2"],
  },
  1.1: {
    id: "1.1",
    category: "Laptops",
    isChecked: false,
    parentId: "1",
    childCheckedCount: 0,
    children: ["1.1.1", "1.1.2", "1.1.3"],
  },
  "1.1.1": {
    id: "1.1.1",
    category: "Asus",
    isChecked: false,
    parentId: "1.1",
  },
  "1.1.2": {
    id: "1.1.2",
    category: "Macbook",
    isChecked: false,
    parentId: "1.1",
  },
  "1.1.3": {
    id: "1.1.3",
    category: "Dell",
    isChecked: false,
    parentId: "1.1",
  },
  1.2: {
    id: "1.2",
    category: "Mobiles",
    isChecked: false,
    parentId: "1",
    childCheckedCount: 0,
    children: ["1.2.1", "1.2.2", "1.2.3"],
  },
  "1.2.1": {
    id: "1.2.1",
    category: "Iphone",
    isChecked: false,
    parentId: "1.2",
  },
  "1.2.2": {
    id: "1.2.2",
    category: "Nothing",
    isChecked: false,
    parentId: "1.2",
  },
  "1.2.3": {
    id: "1.2.3",
    category: "One Plus",
    isChecked: false,
    parentId: "1.2",
  },
};
