export enum RouteId {
  Home,
  Table,
  TicTacToe,
  Stepper,
  Switch,
  InfiniteScroll,
  Bubbles,
  TwoStepAuth,
  TodoList,
  AnalogClock,
  NestedComments,
  TicTacToeNXN,
  NotFound,
}

export enum Routepath {
  Home = "/",
  ticTacToe = "/tic-tac-toe",
  table = "/table",
  stepper = "/stepper",
  switch = "/switch",
  infiniteScroll = "/infinite-scroll",
  bubbles = "/bubbles",
  twoStepAuth = "/twoStepLogin",
  todoList = "/todos",
  analogClock = "/clock",
  nestedComments = "/nested-checkbox",
  ticTacToeNXN = "/tic-tac-toe-NXN",
  NotFound = "*",
}
